### ISSUE TITLE
Integrate Linux input methods

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#30]
Congratulations! You realized my idea before I getting to learn Java. This is exactly what I thought: an optimized common Japanese keyboard on mobile for all languages.

On the desktop, there are four characters for a key: not pressing any other key, Shift, AltGr, Shift+AltGr. So I guess it can be corresponding to the "no direction" and 3 directions.

On Linux they are located at a folder, every language has a XKB file, where its keyboards are stored. It is very easy to customize your keyboards there. There are plenty of layouts.

If you are not familiar with Linux, I recommend you to use Debian in a virtual machine and go to 'usr/share/X11/xkb/symbols/' to find out.

**Comment by Julow** [comment]
Hi! Thanks for the suggestion.
This is harder than it looks, the keyboard currently has dead keys that don't exist in xkb and has custom key combinations and key actions specific to android.

If you want to experiment with this, I'd suggest writing a standalone script that outputs layout descriptions for this app (see [qwerty.xml](https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/qwerty.xml)).

One thing from xkb that I have on my TODO list is the Compose key.

**Comment by GrimPixel** [comment]
I see, in those XML, keys are not expected to be modifier keys.

I think the sequence of typing letter first and then diacritics is better as is the order of writing. The problem is that Compose key means more tapping. I see in O Keyboard, there is an AltGr key but it's used after tapping the letter. So its AltGr recognizes the letter and show available diacritized letters of that one.

**Comment by avently** [comment]
i noticed that the keyboard keys like Ctrl doesn't work in Linux via Anydesk. Since the main purpose of the app to be a helper for developers it's not the best situation and probably needs more attention. You can look at Full Keyboard if you interesting about implementation details. It works ideally

**Comment by Julow** [comment]
@avently I've fixed a bug related to modifier keys (14dabb6) that might fix your problem in Anydesk.

**Comment by sdrapha** [comment]
I don't use Anydesk, but I use Remote Desktop Manager (by Devolutions), and the Ctrl, Alt and Meta keys didn't worked there either. 
I can confirm that now they work with Unexpected Keyboard v 13.0. Huray! 
But the Shift still doesn't unfortunately.

**Comment by Julow** [comment]
Two years later, integrating layouts from other systems is not planned. This app is quite different from linux input methods and layouts must be tailored to it.

The compose key is still planned but need someone to put time into it.

The shift key bug is tracked here: https://github.com/Julow/Unexpected-Keyboard/issues/512

**Comment by Julow** [comment]
Update: The shift key bug is fixed and the compose key is implemented.
